### PR TITLE
refactor (example app): migrate from vanilla RN app to RNTA

### PR DESCRIPTION
**Pull request by kelset**
👋 Edo!

As promised, here's the PR that refactor the existing example app to use [React Native Test App](https://github.com/microsoft/react-native-test-app) instead (which, if you look at the changes, reduces the complexity by a lot - the diff count is wonky because of the -lock file changes). A basic breakdown of the steps I took to do it can be found in this [wiki page](https://github.com/microsoft/react-native-test-app/wiki/Migrate-an-Existing-Test-App), and I've also updated the contributing docs to match.

On top of that, me and @tido64 did a couple of follow up tweaks to make the lib a bit cleaner and better:
* first off, we set up an [Expo config plugin](https://docs.expo.dev/config-plugins/introduction/). This basically means that for any Expo-based app or other apps that support them (like, you guessed it, RNTA), the step of having to modify the `Info.plist` doesn't need to be done manually (you just need to add an entry to the `app.json`).
* I fixed the babel config - when doing this commit https://github.com/sparkfabrik/sparkfabrik-react-native-idfa-aaid/commit/525ff66358949fa83407f31f2bffffd3b391a182 you added the new [`@react-native/babel-preset`](https://github.com/facebook/react-native/tree/main/packages/react-native-babel-preset) but forgot to update the babel-config to match. (also, sidenote, I'm not sure why it's there in the first place since [the reference PR](https://github.com/sparkfabrik/sparkfabrik-react-native-idfa-aaid/pull/68) doesn't have those changes)

Anyway, here's a screenshot of it all working locally:
Screenshot 2024-01-18 at 15 16 40

Try it out and let me know your thoughts!

### CODE REVIEW

**Comment by edodusi** [comment]
Hey @kelset! Thanks for the PR, I started testing it and found a potential issue with the Android run, not sure if it's related to my local setup or to something with RTNA but the way I fixed it makes me think it might be the latter.

So I ran `npm run example:setup` and it finished ok.

Then running `npm run example:android` led to errors because I forgot to run `npm install` on the root folder, so that's a step I would add on the documentation.

Oh, I also saw that after the setup an untracked file is created `example/ios/.xcode.env.local` that I think should be added to the `.gitignore`.

So after running `npm install` the Android setup starts, but it fails with this log:

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/edoardodusi/github/sparkfabrik-react-native-idfa-aaid/example/node_modules/react-native-test-app/test-app.gradle' line: 13

* What went wrong:
A problem occurred evaluating script.
> Failed to apply config plugins:
  node:internal/process/promises:289
              triggerUncaughtException(err, true /* fromPromise */);
              ^

  [Error: [ios.infoPlist]: withIosInfoPlistBaseMod: ENOENT: no such file or directory, open 'node_modules/.generated/ios/ReactTestApp/Info.plist'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: 'node_modules/.generated/ios/ReactTestApp/Info.plist'
  }

  Node.js v20.10.0
```

This seems strange because it mentions an iOS file `Info.plist`, but I'm running an Android build.

So I tried running `npm run example:setup-ios`, the setup finishes correctly, and then when I re-run `npm run example:android` the build finishes and I can run the app on the emulator.

And that's what made me think that it could be related to something in RNTA and not on my local setup.
What do you think?

**Comment by edodusi** [comment]
And I ran into an issue also with the iOS app.

After the ios setup, when running `npm run example:ios` I got this:

```
> npm run example:ios

> @sparkfabrik/react-native-idfa-aaid@1.1.0 example:ios
> cd example && npm run ios


> IDFAExample@0.0.1 ios
> react-native run-ios

error xcodebuild: error: Unable to read project 'example.xcodeproj'.
Error: xcodebuild: error: Unable to read project 'example.xcodeproj'.
```

If I open the project directly in xcode it works, so the issue is only with the command line.

I don't know it this is an issue with RTNA or with my local setup, posting the complete info just in case:

```
> npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1
  Memory: 66.06 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /Users/edoardodusi/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-28 | Google APIs ARM 64 v8a
      - android-30 | Intel x86 Atom_64
      - android-32 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/edoardodusi/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

**Comment by kelset** [comment]
Ciao Edo, thanks for the report!

> Then running `npm run example:android` led to errors because I forgot to run `npm install` on the root folder, so that's a step I would add on the documentation.

It's already there ;) https://github.com/kelset/sparkfabrik-react-native-idfa-aaid/blob/kelset/add-rnta-3/CONTRIBUTING.md#development-workflow

screenshot:
Screenshot 2024-01-19 at 13 35 21

re: for the local files yes, it looks like it's something local on your end, I can't see them. When changing branches I always recommend running `git clean -fdx` to ensure that you fully wipe the local files and only have what's tracked by git :)

re: the expo plugin issue, @tido64 is already on the case https://github.com/microsoft/react-native-test-app/pull/1784 :) thanks for noticing and the report! As soon as it's merged & released I'll bump the RNTA version in the deps and then we should be good to go :)

**Comment by edodusi** [comment]
Thanks @kelset and @tido64! I will re-run both apps when you update this, keep me posted ;)

**Comment by kelset** [comment]
@edodusi commit added, try again ;) (...but do a `git clean -fdx` first :D )

**Comment by edodusi** [comment]
@kelset tested with both builds and everything workked 🎉 

I will merge this. I was about to report the error with `example:Android` but I see @tido64 already opened the same issue on the CLI so I can only confirm.

Thanks!

**Pull request merged**
